### ISSUE TITLE
Need instructions on how to import to IDE/compile/install

### ISSUE THREAD

**Issue by reoseah** [Nuclearfarts/retro-tater#1]
There're no instruction given. So, I tried to explore available Gradle commands myself using `./gradlew tasks` and was quickly met by 
```
* Where:
Build file 'C:\Users\reose\Documents\GitHub\retro-tater\build.gradle' line: 2

* What went wrong:
Plugin [id: 'fabric-loom', version: '0.2.7-CURSEDFORGE'] was not found in any of the following sources:

- Gradle Core Plugins (not a core plugin, please see https://docs.gradle.org/4.10.3/userguide/standard_plugins.html for available core plugins)
- Plugin Repositories (could not resolve plugin artifact 'fabric-loom:fabric-loom.gradle.plugin:0.2.7-CURSEDFORGE')
  Searched in the following repositories:
    BintrayJCenter
    Fabric(https://maven.fabricmc.net/)
    Gradle Central Plugin Repository
    MavenLocal(file:/C:/Users/reose/.m2/repository)
```

**Comment by reoseah** [comment]
So, I solved that by having "1.4.7" branch of yours fabric loom repo compiled and published to local maven. Now I have this
```
* What went wrong:
A problem occurred configuring root project 'retro-tater'.
> Failed to notify project evaluation listener.
   > Failed to provide net.minecraftforge:mcp:726a : Could not resolve all files for configuration ':mappings'.
   > java.lang.NullPointerException (no error message)
```

**Comment by TwilightFlower** [comment]
You need to grab the MCP 726a zip (I believe the Minecraft Wiki has an archive of it) and depend on it by either putting it into your local maven at that coordinate, or I believe a file dependency will work (I have not touched this in just over a year, as you can see by the commit date.)

**Comment by reoseah** [comment]
I'll try that. I have mcp726a.zip, but when I saw Gradle asking for a .jar file, I assumed the zip and jar are some different things...

**Comment by reoseah** [comment]
So, I downloaded mcp726a.zip and successfully installed it into my local maven repo with this command:
```sh
mvn install:install-file -Dfile=mcp726a.zip -DgroupId=net.minecraftforge -DartifactId=mcp -Dversion=726a -Dpackaging=zip
```
Now I'm getting this error:
```
PS C:\Users\reose\Documents\GitHub\retro-tater> .\gradlew genSources eclipse

> Configure project :
Fabric Loom: 0.2.7-CURSEDFORGE Build(local)
:setting up loom dependencies
:setting up mappings (mcp 726a)
Using project based jar storage

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'retro-tater'.
> Could not resolve all files for configuration ':modRuntime'.
   > Could not find voldeloom-adapter.jar (io.github.nuclearfarts:voldeloom-adapter:1.0.0).
     Searched in the following locations:
         https://files.minecraftforge.net/maven/io/github/nuclearfarts/voldeloom-adapter/1.0.0/voldeloom-adapter-1.0.0.jar

```

**Comment by reoseah** [comment]
I think this is an issue:
https://jitpack.io/com/github/Nuclearfarts/voldeloom-adapter/master-1cbbd61fce-1/build.log

JitPack can't compile https://github.com/Nuclearfarts/voldeloom-adapter repo

```java
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'build'.
> Failed to notify project evaluation listener.
   > Failed to provide net.minecraftforge:mcp:726a : Could not resolve all files for configuration ':mappings'.
   > java.lang.NullPointerException (no error message)

```

**Comment by reoseah** [comment]
I've cloned that repo and tried to compile it manually, I get this error on `./gradlew build`
```
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find minecraft.jar (net.minecraft:minecraft:1.4.7-forge-1.4.7-6.6.2.534-projectmapped-net.minecraftforge.mcp-726a).
  Searched in the following locations:
      https://files.minecraftforge.net/maven/net/minecraft/minecraft/1.4.7-forge-1.4.7-6.6.2.534-projectmapped-net.minecraftforge.mcp-726a/minecraft-1.4.7-forge-1.4.7-6.6.2.534-projectmapped-net.minecraftforge.mcp-726a.jar
> Could not find fabric-loader.jar (net.fabricmc:fabric-loader:0.7.8+build.187@net.minecraftforge.mcp.1_4_7_forge_1_4_7_6_6_2_534.726a).
  Searched in the following locations:
      https://files.minecraftforge.net/maven/net/fabricmc/fabric-loader/0.7.8+build.187@net.minecraftforge.mcp.1_4_7_forge_1_4_7_6_6_2_534.726a/fabric-loader-0.7.8+build.187@net.minecraftforge.mcp.1_4_7_forge_1_4_7_6_6_2_534.726a.jar
 ```

**Comment by reoseah** [comment]
Anyway, I was just having a little fun, but I did figure out how to make forge 1.4.7 environment:
- download 1.4.7 client and server from wiki, forge sources archive, `mcp726a.zip` and Forge dependencies (`argo-2.25`, `asm-all-4.0`, `asm-all-4.0-source`, `bcprov-jdk15on-147.jar`, `guava-12.0.1.jar` and `guava-12.0.1-sources.jar`, note that they pluralized `source`, so search without that in internet, then change the file name when saving... all of them are easily searchable from public maven repos)
- extract forge folder out of its zip
- in the forge folder, create `mcp` folder and extract there the mcp archive
- in mcp folder, put server jar named `minecraft_server.jar` into `jars` and client jar named `minecraft.jar` into `jars/bin`
- also in mcp folder, put all forge dependencies into `lib`
- go to `patches` folder, find `RenderPlayer.patch`, at the bottom of it change `var21` to `var22` in two places...
- run `install.bat` or `install.sh`
- somewhere in forge launching code, it will fail to calculate md5 check for its dependencies and crash, find that throw statement and comment it out
- in eclipse, switch workspace to `forge/mcp/eclipse` folder (not a `forge/fml/eclipse`, that one doesn't work)
